# Generated by Django 5.0.1 on 2024-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_filepaths_path_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="filepaths",
            name="html_content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
